{
 "title": "Spring Boot Advanced Monitoring",
 "tags": [
  "spring-boot",
  "micrometer",
  "actuator"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Throughput (API Requests/sec)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "CPU Usage (Process)",
   "type": "gauge",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "Process" }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "gauge",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "System" }
   ]
  },
  {
   "title": "Top Endpoints (Traffic)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 7, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Status Breakdown",
   "type": "piechart",
   "gridPos": { "x": 12, "y": 7, "w": 12, "h": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_server_requests_seconds_count[1h]))",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 17, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\"}",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "HikariCP Pool Usage",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 17, "w": 12, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "hikaricp_connections_max", "legendFormat": "Max" },
    { "expr": "hikaricp_connections_active", "legendFormat": "Active" },
    { "expr": "hikaricp_connections_idle", "legendFormat": "Idle" }
   ]
  },
  {
   "title": "Tổng Order Đã Đặt Thành Công",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "sum(orders_placed_total_total)" }
   ]
  }
 ]
}